import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'vite';import react from '@vitejs/plugin-react';
import {JSDOM} from 'jsdom';
const member={ID:'A1',Nama:'Anggota Satu',Status:'Aktif'};const activity={ID:'K1',NamaKegiatan:'Latihan',Tanggal:'2026-10-03',Status:'Berjalan',AbsensiMulai:'08:00',AbsensiSelesai:'10:00'};
const root=new URL('../',import.meta.url).pathname;
const bundle=await build({root,configFile:false,define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent',plugins:[react()],build:{write:false,lib:{entry:root+'src/main.jsx',name:'TestApp',formats:['iife']}}});
const code=(Array.isArray(bundle)?bundle[0]:bundle).output.find(x=>x.type==='chunk').code;
async function setup(path,{role='ADMIN'}={}){const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost'+path,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;const requests=[];w.localStorage.setItem('saka_session_token','test');w.confirm=()=>true;w.fetch=async(url,opt)=>{if(url==='/api/health')return {ok:true,json:async()=>({ok:true})};const req=JSON.parse(opt.body);requests.push(req);let data={};switch(req.action){case 'auth.me':data={user:{ID:'U1',Nama:'Admin',Role:role}};break;case 'dashboard.get':data={dashboard:{},visibleModules:{},workflow:{approval:{available:true,count:2},attendance:{available:true,count:1,kegiatanId:'K1'},reports:{available:true,count:3,kegiatanId:'K1'}}};break;case 'permissions.get':data={modules:['kas'],rows:[{Role:'PENGURUS',Module:'kas',CanView:'TRUE',CanCreate:'TRUE'},{Role:'ANGGOTA',Module:'kas',CanView:'FALSE'}]};break;case 'modules.get':data={modules:{anggota:[member],kegiatan:[activity],absensi:[{ID:'H1',KegiatanID:'K1',AnggotaID:'A1',NamaAnggota:member.Nama,StatusKehadiran:'Sakit',Catatan:'Dokter'}],inventaris:[{ID:'B1',NamaBarang:'Tenda',Jumlah:5}]}};break;case 'notifications.get':data={items:[{id:'abc',recordId:'I1',targetId:'K1',kind:'permission-pending',module:'absensi',title:'Izin',detail:'Bukti perlu ditinjau'}],unread:1};break;case 'notifications.permissionDetail':data={ID:'I1',NamaAnggota:member.Nama,Status:'Menunggu Verifikasi',BuktiNamaFile:'bukti.png'};break;case 'permission.proofPreview':data={dataUrl:'data:image/png;base64,aGVsbG8=',mimeType:'image/png'};break;case 'assessment.month':data={rows:[member],entries:[],components:[]};break;case 'assessment.skk':data={member,catalog:[{ID:'M1',Butir:'Navigasi'}],completion:[]};break;case 'activity.report.get':data={laporan:{},dokumentasi:[{ID:'D1',NamaFile:'Foto Satu.jpg'}],inventarisKegiatan:[{ID:'R1',InventarisID:'B1',NamaBarang:'Tenda',JumlahDipakai:2,StatusPemakaian:'Dipakai',Versi:'v1'}]};break;case 'activity.documentation.preview':data={dataUrl:'data:image/png;base64,aGVsbG8=',mimeType:'image/png',name:'Foto Satu.jpg'};break;case 'activity.permissionSummary':case 'permission.batch.get':data=[{ID:'I1',Status:'Menunggu Verifikasi'},{ID:'I2',Status:'Disetujui'}];break;case 'crud.kegiatan.save':await new Promise(r=>setTimeout(r,40));return {ok:true,status:200,json:async()=>({ok:false,message:'Tanggal tidak valid'})};}return {ok:true,status:200,json:async()=>({ok:true,data})};};w.eval(code);await wait(()=>w.document.querySelector('.content'));await new Promise(r=>setTimeout(r,30));return {dom,w,requests};}
async function wait(fn){for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('DOM condition timed out');}
function button(w,text,scope=w.document){const el=[...scope.querySelectorAll('button')].find(x=>x.textContent.trim()===text);assert(el,'Missing button '+text);el.click();}
function field(w,label){return [...w.document.querySelectorAll('label')].find(x=>x.querySelector('span')?.textContent.replace(' *','')===label)?.querySelector('input,select,textarea');}
function change(w,el,value){assert(el,'Missing input');const proto=el.tagName==='SELECT'?w.HTMLSelectElement.prototype:w.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,value);el.dispatchEvent(new w.Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));}
test('new activity form retains typed values when backend rejects save',async()=>{const {dom,w}=await setup('/kegiatan');try{button(w,'+ Tambah Kegiatan');await wait(()=>field(w,'Nama Kegiatan'));change(w,field(w,'Nama Kegiatan'),'Acara Baru');change(w,field(w,'Tanggal'),'2026-10-03');w.document.querySelector('[role=dialog] form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,100));assert(w.document.querySelector('[role=dialog]'),'Failure must keep form open');assert.equal(field(w,'Nama Kegiatan').value,'Acara Baru');}finally{dom.window.close();}});
test('action center uses record ID and evidence service',async()=>{const {dom,w,requests}=await setup('/notifications');try{await wait(()=>w.document.querySelector('.data-table'));button(w,'Detail');await wait(()=>[...w.document.querySelectorAll('button')].some(x=>x.textContent==='Lihat Bukti'));button(w,'Lihat Bukti');await new Promise(r=>setTimeout(r,50));assert.equal(requests.find(x=>x.action==='notifications.permissionDetail')?.payload.id,'I1');assert(requests.some(x=>x.action==='permission.proofPreview'));}finally{dom.window.close();}});
test('SKK submission sends Checked true to backend',async()=>{const {dom,w,requests}=await setup('/penilaian');try{await wait(()=>w.document.querySelector('.data-table'));button(w,'Checklist SKK');await wait(()=>w.document.querySelector('[type=checkbox]'));w.document.querySelector('[type=checkbox]').click();await new Promise(r=>setTimeout(r,10));button(w,'Simpan Checklist');await wait(()=>requests.some(x=>x.action==='assessment.skk.save'));assert.equal(requests.find(x=>x.action==='assessment.skk.save').payload.changes[0].Checked,true);}finally{dom.window.close();}});
test('inventory return exposes quantity and damage fields',async()=>{const {dom,w}=await setup('/activity-details');try{await wait(()=>w.document.querySelector('.activity-picker select:last-child option[value=K1]'));change(w,w.document.querySelector('.activity-picker select:last-child'),'K1');await wait(()=>w.document.querySelector('.data-table'));button(w,'Edit',w.document.querySelector('.data-table'));await wait(()=>w.document.querySelector('[role=dialog]'));assert(field(w,'Jumlah Kembali'));assert(field(w,'Jumlah Rusak Kembali'));}finally{dom.window.close();}});
test('detail hero attendance button navigates to selected activity',async()=>{const {dom,w}=await setup('/activity-details');try{await wait(()=>w.document.querySelector('.activity-picker select:last-child option[value=K1]'));change(w,w.document.querySelector('.activity-picker select:last-child'),'K1');await wait(()=>w.document.querySelector('.activity-detail-hero'));button(w,'Absen',w.document.querySelector('.activity-detail-hero'));await new Promise(r=>setTimeout(r,30));assert.equal(w.location.pathname+w.location.search,'/absensi?kegiatanId=K1');}finally{dom.window.close();}});
test('permission editor sends only the selected role',async()=>{const {dom,w,requests}=await setup('/permissions');try{await wait(()=>w.document.querySelector('.data-table'));button(w,'Simpan Permission');await wait(()=>requests.some(x=>x.action==='permissions.save'));const sent=requests.find(x=>x.action==='permissions.save').payload.rows;assert(sent.every(x=>x.Role==='PENGURUS'));}finally{dom.window.close();}});
test('global search opens a matching menu',async()=>{const {dom,w}=await setup('/dashboard');try{const input=w.document.querySelector('.global-search input');change(w,input,'inventaris');await wait(()=>w.document.querySelector('.search-results a'));const links=[...w.document.querySelectorAll('.search-results a')];assert(links.some(x=>x.href.includes('/inventaris')));}finally{dom.window.close();}});
test('notification bell opens action center',async()=>{const {dom,w}=await setup('/dashboard');try{const bell=w.document.querySelector('.topbar-actions a');assert(bell,'Notification link missing');bell.click();await new Promise(r=>setTimeout(r,30));assert.equal(w.location.pathname,'/notifications');}finally{dom.window.close();}});
test('documentation preview is displayed inside the app',async()=>{const {dom,w}=await setup('/activity-details?kegiatanId=K1');try{await wait(()=>[...w.document.querySelectorAll('button')].some(x=>x.textContent==='Preview'));button(w,'Preview');await wait(()=>w.document.querySelector('[role=dialog] img'));assert(w.document.querySelector('[role=dialog] img').src.startsWith('data:image/'));}finally{dom.window.close();}});
test('permission summary displays actual counts from backend rows',async()=>{const {dom,w}=await setup('/activity-details?kegiatanId=K1');try{await wait(()=>w.document.querySelector('.compact-stats'));await new Promise(r=>setTimeout(r,30));assert.deepEqual([...w.document.querySelectorAll('.compact-stats strong')].map(x=>x.textContent),['2','1','1','0']);}finally{dom.window.close();}});
test('staff assessment does not show administrator-only entry controls',async()=>{const {dom,w}=await setup('/penilaian',{role:'PENGURUS'});try{assert(![...w.document.querySelectorAll('button')].some(x=>x.textContent==='+ Input Nilai'));assert(![...w.document.querySelectorAll('button')].some(x=>x.textContent==='+ Komponen'));}finally{dom.window.close();}});
test('attendance bulk editor preserves existing sickness status',async()=>{const {dom,w}=await setup('/absensi?kegiatanId=K1');try{await wait(()=>w.document.querySelector('.data-table select'));assert.equal(w.document.querySelector('.data-table select').value,'Sakit');}finally{dom.window.close();}});
test('unlinked administrator profile never shows first member identity',async()=>{const {dom,w}=await setup('/profil');try{await wait(()=>w.document.querySelector('.profile-summary h2')?.textContent==='Admin');assert.equal(w.document.querySelector('.profile-summary h2').textContent,'Admin');}finally{dom.window.close();}});

test('workflow cards display backend counts and navigate to the selected activity',async()=>{const {dom,w}=await setup('/dashboard');try{const cards=[...w.document.querySelectorAll('.workflow-modern a')];assert.equal(cards.length,3);assert.deepEqual(cards.map(x=>x.querySelector('strong')?.textContent),['2','1','3']);assert.equal(new URL(cards[0].href).pathname,'/notifications');cards[1].click();await new Promise(r=>setTimeout(r,30));assert.equal(w.location.pathname+w.location.search,'/absensi?kegiatanId=K1');}finally{dom.window.close();}});

for (const role of ['ADMIN','PENGURUS','ANGGOTA']) test(`mobile Logout clears session and opens login for ${role}`,async()=>{const {dom,w,requests}=await setup('/dashboard',{role});try{const logout=w.document.querySelector('.mobile-nav button[aria-label="Logout"]');assert(logout,'Mobile navigation must expose Logout');assert.equal(logout.textContent.trim(),'Logout');logout.click();await wait(()=>w.document.querySelector('.login-card'));assert.equal(w.localStorage.getItem('saka_session_token'),null);assert.equal(w.localStorage.getItem('saka_session'),null);assert(requests.some(r=>r.action==='auth.logout'));assert.equal(w.location.pathname,'/login');}finally{dom.window.close();}});
