import {useState} from 'react';import PageHeader from '../../components/common/PageHeader';import DataTable from '../../components/common/DataTable';import CrudModal from '../../components/common/CrudModal';import {moduleService} from '../../services/module.service';import {step2Service} from '../../services/step2.service';import {useRemoteData} from '../../hooks/useRemoteData';
const toFile=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res({name:f.name,mimeType:f.type,base64:String(r.result).split(',')[1]});r.onerror=rej;r.readAsDataURL(f)});
const today=()=>new Date().toISOString().slice(0,10);
export default function Page(){const {data:acts}=useRemoteData(()=>moduleService.activities(),[]),{data:inventory}=useRemoteData(()=>moduleService.inventory(),[]);const [kid,setKid]=useState(''),[data,setData]=useState(null),[modal,setModal]=useState(null),[editing,setEditing]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const uses=data?.inventarisKegiatan||[],docs=data?.dokumentasi||[],report=data?.laporan||{};
 async function load(id=kid){if(!id)return;setBusy(true);try{setData(await step2Service.report(id));setMsg('')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function act(fn,ok){setBusy(true);try{await fn();if(ok)setMsg(ok);await load()}catch(e){setMsg(e.message);throw e}finally{setBusy(false)}}
 async function upload(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>2400*1024){setMsg('Foto maksimum sekitar 2,3 MB.');return}try{await act(async()=>step2Service.uploadDoc(kid,{...(await toFile(file)),keterangan:''}),'Dokumentasi diunggah.')}catch(_){}}
 async function invPhoto(r,phase,file){if(!file)return;if(file.size>2400*1024){setMsg('Foto maksimum sekitar 2,3 MB.');return}try{const payload=await toFile(file);await act(()=>step2Service.uploadInventoryPhoto(kid,r.ID,phase,payload),'Foto kondisi inventaris tersimpan.')}catch(_){}}
 async function pdf(){try{const x=await act(()=>step2Service.generateReportPdf(kid),'PDF laporan berhasil dibuat.');if(x?.url)window.open(x.url,'_blank','noopener,noreferrer')}catch(_){}}
 const invFields=[{key:'InventarisID',label:'Barang',type:'select',required:true,options:(inventory||[]).map(x=>({value:x.ID,label:`${x.NamaBarang} (tersedia ${x.Tersedia??x.Jumlah??0})`}))},{key:'JumlahDipakai',label:'Jumlah Dipakai',type:'number',min:'1',required:true},{key:'StatusPemakaian',label:'Status',type:'select',options:['Dipakai','Selesai']},{key:'Keterangan',label:'Keterangan',type:'textarea',full:true}];
 const reportFields=[{key:'JamMulai',label:'Jam Mulai',type:'time'},{key:'JamSelesai',label:'Jam Selesai',type:'time'},{key:'Cuaca',label:'Cuaca',type:'select',options:['Cerah','Berawan','Mendung','Hujan','Hujan Lebat','Lainnya']},{key:'JumlahPamongInstruktur',label:'Jumlah Pamong/Instruktur',type:'number',min:'0'},{key:'FokusKrida',label:'Fokus Krida'},{key:'TopikMateri',label:'Topik Materi',type:'textarea',full:true},{key:'Instruktur',label:'Instruktur/Pemateri'},{key:'Pencapaian',label:'Pencapaian',type:'textarea',full:true},{key:'Kendala',label:'Kendala',type:'textarea',full:true},{key:'TindakLanjut',label:'Tindak Lanjut',type:'textarea',full:true},{key:'TempatLaporan',label:'Tempat Laporan'},{key:'TanggalLaporan',label:'Tanggal Laporan',type:'date'},{key:'Penandatangan1Nama',label:'Penandatangan 1'},{key:'Penandatangan1Jabatan',label:'Jabatan 1'},{key:'Penandatangan2Nama',label:'Penandatangan 2'},{key:'Penandatangan2Jabatan',label:'Jabatan 2'}];
 const docFields=[{key:'Keterangan',label:'Keterangan',type:'textarea',full:true},{key:'Urutan',label:'Urutan',type:'number',min:'1'}];
 const invCols=[{key:'NamaBarang',label:'Barang'},{key:'JumlahDipakai',label:'Dipakai'},{key:'JumlahKembali',label:'Kembali'},{key:'StatusPemakaian',label:'Status'},{key:'_',label:'Aksi',render:(_,r)=><div className="row-actions"><button className="btn small" onClick={()=>{setEditing(r);setModal('inv')}}>Edit</button><label className="btn small">Foto Awal<input hidden type="file" accept="image/*" onChange={e=>invPhoto(r,'Awal',e.target.files?.[0])}/></label><label className="btn small">Foto Setelah<input hidden type="file" accept="image/*" onChange={e=>invPhoto(r,'Setelah',e.target.files?.[0])}/></label><button className="btn small danger" onClick={()=>confirm('Hapus pemakaian barang ini?')&&act(()=>step2Service.deleteActivityInventory(r.ID),'Riwayat inventaris dihapus.')}>Hapus</button></div>}];
 const docCols=[{key:'NamaFile',label:'File'},{key:'Keterangan',label:'Keterangan'},{key:'Uploader',label:'Uploader'},{key:'Urutan',label:'Urutan'},{key:'_',label:'Aksi',render:(_,r)=><div className="row-actions"><button className="btn small" onClick={async()=>{try{const x=await step2Service.previewDoc(r.ID);if(x?.dataUrl)window.open(x.dataUrl,'_blank')}catch(e){setMsg(e.message)}}}>Preview</button><button className="btn small" onClick={()=>{setEditing(r);setModal('doc')}}>Edit</button><button className="btn small danger" onClick={()=>confirm('Hapus dokumentasi ini?')&&act(()=>step2Service.deleteDoc(r.ID),'Dokumentasi dihapus.')}>Hapus</button></div>}];
 return <><PageHeader eyebrow="DETAIL KEGIATAN" title="Detail & Laporan Kegiatan" description="Inventaris, dokumentasi, laporan kegiatan, dan PDF dalam satu halaman."/><section className="panel"><label>Kegiatan <select value={kid} onChange={e=>{setKid(e.target.value);load(e.target.value)}}><option value="">Pilih...</option>{(acts||[]).map(x=><option key={x.ID} value={x.ID}>{x.NamaKegiatan} — {x.Tanggal}</option>)}</select></label>{msg&&<div className="alert">{msg}</div>}</section>
 {kid&&<><section className="panel section-gap"><div className="toolbar toolbar-between"><h2>Pemakaian Inventaris</h2><button className="btn" onClick={()=>{setEditing(null);setModal('inv')}}>+ Catat Barang</button></div><DataTable columns={invCols} rows={uses} empty="Belum ada pemakaian inventaris."/></section>
 <section className="panel section-gap"><div className="toolbar toolbar-between"><h2>Dokumentasi</h2><label className="btn">+ Upload Foto<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/></label></div><DataTable columns={docCols} rows={docs} empty="Belum ada dokumentasi."/></section>
 <section className="panel section-gap"><div className="toolbar toolbar-between"><div><h2>Laporan Kegiatan</h2><span className="muted">{report?.PDFUrl?'PDF laporan sudah tersedia.':'Lengkapi laporan sebelum membuat PDF.'}</span></div><div className="row-actions"><button className="btn" onClick={()=>{setEditing(report);setModal('report')}}>Isi / Edit Laporan</button><button className="btn primary" onClick={pdf}>Generate PDF</button></div></div></section></>}
 <CrudModal open={modal==='inv'} title={editing?'Edit Pemakaian Inventaris':'Catat Pemakaian Inventaris'} fields={invFields} initial={editing||{StatusPemakaian:'Dipakai'}} saving={busy} onClose={()=>{setModal(null);setEditing(null)}} onSave={async x=>{try{await act(()=>step2Service.saveActivityInventory(kid,x),'Inventaris tersimpan.');setModal(null);setEditing(null)}catch(_){}}}/>
 <CrudModal open={modal==='doc'} title="Edit Dokumentasi" fields={docFields} initial={editing||{}} saving={busy} onClose={()=>{setModal(null);setEditing(null)}} onSave={async x=>{try{await act(()=>step2Service.updateDoc(editing.ID,x),'Dokumentasi diperbarui.');setModal(null);setEditing(null)}catch(_){}}}/>
 <CrudModal open={modal==='report'} title="Laporan Kegiatan" fields={reportFields} initial={{...report,TanggalLaporan:report.TanggalLaporan||today()}} saving={busy} onClose={()=>setModal(null)} onSave={async x=>{try{await act(()=>step2Service.saveReport(kid,x),'Laporan tersimpan.');setModal(null)}catch(_){}}}/></>}
