import {useMemo,useState} from 'react';import PageHeader from '../../components/common/PageHeader';import DataTable from '../../components/common/DataTable';import CrudModal from '../../components/common/CrudModal';import {moduleService} from '../../services/module.service';import {crudService} from '../../services/crud.service';import {operationsService} from '../../services/operations.service';import {useRemoteData} from '../../hooks/useRemoteData';
const fields=[{key:'NamaKegiatan',label:'Nama Kegiatan',required:true},{key:'Tanggal',label:'Tanggal',type:'date',required:true},{key:'Jenis',label:'Jenis',type:'select',options:['Latihan','Rapat','Pendidikan','Bakti Sosial','Kunjungan','Upacara','Lainnya']},{key:'Lokasi',label:'Lokasi'},{key:'PenanggungJawab',label:'Penanggung Jawab'},{key:'AbsensiMulai',label:'Absensi Mulai',type:'time'},{key:'AbsensiSelesai',label:'Absensi Selesai',type:'time'},{key:'RadiusAktif',label:'Radius',type:'select',options:['Aktif','Nonaktif']},{key:'AbsensiLatitude',label:'Latitude',type:'number',step:'any'},{key:'AbsensiLongitude',label:'Longitude',type:'number',step:'any'},{key:'AbsensiRadiusMeter',label:'Radius Meter',type:'number',min:'1'}];
export default function Page(){const {data,loading,error,reload}=useRemoteData(()=>moduleService.activities(),[]);const [modal,setModal]=useState(false),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function run(fn){setBusy(true);setMsg('');try{await fn();await reload()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function save(x){await run(()=>crudService.save('kegiatan',x));setModal(false)}
 async function del(r){if(confirm('Hapus kegiatan ini?'))await run(()=>crudService.remove('kegiatan',r.ID))}
 async function trans(r,target){let alasan='';if(target==='Dibatalkan'){alasan=prompt('Alasan pembatalan:')||'';if(!alasan)return}await run(()=>operationsService.transition(r.ID,target,alasan))}
 async function rule(r){const days=prompt('Batas izin mulai H-berapa?',String(r.BatasIzinHari||3));if(days===null)return;const time=prompt('Jam tutup izin Hari H (HH:mm):',String(r.JamTutupIzin||'07:00'));if(time===null)return;const hh=confirm('Izinkan pengajuan pada Hari H?');await run(()=>operationsService.updateIzinRule({ID:r.ID,BatasIzinHari:Number(days),IzinHariH:hh,JamTutupIzin:time}))}
 const cols=useMemo(()=>[{key:'NamaKegiatan',label:'Kegiatan'},{key:'Tanggal',label:'Tanggal'},{key:'Status',label:'Status'},{key:'__',label:'Aksi',render:(_,r)=><div className="row-actions"><button className="btn small" onClick={()=>{setEditing(r);setModal(true)}}>Edit</button>{r.Status==='Rencana'&&<button className="btn small" onClick={()=>trans(r,'Berjalan')}>Mulai</button>}{r.Status==='Berjalan'&&<button className="btn small" onClick={()=>trans(r,'Selesai')}>Selesai</button>}{!['Selesai','Dibatalkan'].includes(r.Status)&&<button className="btn small" onClick={()=>trans(r,'Dibatalkan')}>Batalkan</button>}<button className="btn small" onClick={()=>rule(r)}>Atur Izin</button><button className="btn small" onClick={async()=>{try{const x=await operationsService.attendanceLink?.(r.ID);if(x?.url)navigator.clipboard.writeText(x.url)}catch(_){}}}>Link Absen</button><button className="btn small danger" onClick={()=>del(r)}>Hapus</button></div>}],[]);
 return <><PageHeader eyebrow="KEGIATAN" title="Kegiatan" description="Kelola kegiatan, status operasional, radius, dan aturan izin."/><section className="panel"><div className="toolbar"><span>{loading?'Memuat...':`${(data||[]).length} kegiatan`}</span><button className="btn primary" onClick={()=>{setEditing(null);setModal(true)}}>+ Tambah Kegiatan</button></div>{(error||msg)&&<div className="alert">{error||msg}</div>}<DataTable columns={cols} rows={data||[]} empty="Belum ada kegiatan."/></section><CrudModal open={modal} title={editing?'Edit Kegiatan':'Tambah Kegiatan'} fields={fields} initial={editing||{}} saving={busy} onClose={()=>setModal(false)} onSave={save}/></>}
