import {useState} from 'react';import PageHeader from '../../components/common/PageHeader';import DataTable from '../../components/common/DataTable';import CrudModal from '../../components/common/CrudModal';import {moduleService} from '../../services/module.service';import {step2Service} from '../../services/step2.service';import {useRemoteData} from '../../hooks/useRemoteData';
const toFile=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res({name:f.name,mimeType:f.type,base64:String(r.result).split(',')[1]});r.onerror=rej;r.readAsDataURL(f)});
export default function Page(){const {data:acts}=useRemoteData(()=>moduleService.activities(),[]),{data:inventory}=useRemoteData(()=>moduleService.inventory(),[]);const [kid,setKid]=useState(''),[uses,setUses]=useState([]),[report,setReport]=useState(null),[modal,setModal]=useState(false),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function load(id=kid){if(!id)return;setBusy(true);try{setUses(await step2Service.activityInventory(id)||[]);setReport(await step2Service.report(id));setMsg('')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function saveUse(x){setBusy(true);try{await step2Service.saveActivityInventory(kid,x);setModal(false);await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function upload(e){const file=e.target.files?.[0];if(!file)return;if(file.size>2400*1024){setMsg('Foto maksimal sekitar 2,3 MB. Kompres foto terlebih dahulu.');return}setBusy(true);try{await step2Service.uploadDoc(kid,{...(await toFile(file)),keterangan:''});await load();setMsg('Dokumentasi berhasil diunggah.')}catch(x){setMsg(x.message)}finally{setBusy(false);e.target.value=''}}
 async function saveReport(){const x={JamMulai:prompt('Jam mulai',report?.report?.JamMulai||''),JamSelesai:prompt('Jam selesai',report?.report?.JamSelesai||''),Cuaca:prompt('Cuaca',report?.report?.Cuaca||'Cerah'),FokusKrida:prompt('Fokus Krida',report?.report?.FokusKrida||''),TopikMateri:prompt('Topik materi',report?.report?.TopikMateri||''),Instruktur:prompt('Instruktur',report?.report?.Instruktur||''),Pencapaian:prompt('Pencapaian',report?.report?.Pencapaian||''),Kendala:prompt('Kendala',report?.report?.Kendala||''),TindakLanjut:prompt('Tindak lanjut',report?.report?.TindakLanjut||'')};setBusy(true);try{await step2Service.saveReport(kid,x);await load();setMsg('Laporan kegiatan tersimpan.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const fields=[{key:'InventarisID',label:'Barang',type:'select',required:true,options:(inventory||[]).map(x=>({value:x.ID,label:`${x.NamaBarang} (tersedia ${x.Tersedia??x.Jumlah??0})`}))},{key:'JumlahDipakai',label:'Jumlah Dipakai',type:'number',min:'1',required:true},{key:'StatusPemakaian',label:'Status',type:'select',options:['Dipakai','Selesai']},{key:'Keterangan',label:'Keterangan',type:'textarea',full:true}];
 const cols=[{key:'NamaBarang',label:'Barang'},{key:'JumlahDipakai',label:'Dipakai'},{key:'StatusPemakaian',label:'Status'},{key:'Keterangan',label:'Keterangan'}];
 return <><PageHeader eyebrow="DETAIL KEGIATAN" title="Inventaris, Dokumentasi & Laporan" description="Kelola kelengkapan kegiatan dari satu halaman."/><section className="panel"><label>Kegiatan <select value={kid} onChange={e=>{setKid(e.target.value);load(e.target.value)}}><option value="">Pilih...</option>{(acts||[]).map(x=><option key={x.ID} value={x.ID}>{x.NamaKegiatan} — {x.Tanggal}</option>)}</select></label>{msg&&<div className="alert">{msg}</div>}{kid&&<><div className="toolbar"><h3>Pemakaian Inventaris</h3><button className="btn" onClick={()=>setModal(true)}>+ Catat Barang</button></div><DataTable columns={cols} rows={uses} empty="Belum ada pemakaian inventaris."/><div className="toolbar"><h3>Dokumentasi</h3><label className="btn">Upload Foto<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/></label></div><p>Foto kegiatan disimpan ke Google Drive melalui backend GAS.</p><div className="toolbar"><h3>Laporan Kegiatan</h3><button className="btn primary" disabled={busy} onClick={saveReport}>Isi / Perbarui Laporan</button></div></>}</section><CrudModal open={modal} title="Pemakaian Inventaris" fields={fields} initial={{StatusPemakaian:'Dipakai'}} saving={busy} onClose={()=>setModal(false)} onSave={saveUse}/></>}
