import {useEffect,useMemo,useState} from 'react';import PageHeader from '../../components/common/PageHeader';import DataTable from '../../components/common/DataTable';import {moduleService} from '../../services/module.service';import {operationsService} from '../../services/operations.service';import {useRemoteData} from '../../hooks/useRemoteData';
export default function Page(){const {data:members}=useRemoteData(()=>moduleService.members(),[]),{data:acts}=useRemoteData(()=>moduleService.activities(),[]);const [kid,setKid]=useState(''),[rows,setRows]=useState([]),[izin,setIzin]=useState([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{setRows((members||[]).filter(x=>['Aktif','Calon Anggota'].includes(x.Status)).map(x=>({AnggotaID:x.ID,Nama:x.Nama,StatusKehadiran:'Hadir',Catatan:''})))},[members]);
 async function loadIzin(){if(!kid)return;setBusy(true);try{const x=await operationsService.getPermissions(kid);setIzin(Array.isArray(x)?x:[]);setMsg('')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 useEffect(()=>{loadIzin()},[kid]);
 async function save(){if(!kid)return;setBusy(true);try{await operationsService.saveBatchAttendance(kid,rows.map(({AnggotaID,StatusKehadiran,Catatan})=>({AnggotaID,StatusKehadiran,Catatan})));setMsg('Absensi massal berhasil disimpan.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function verify(x,d){let note='';if(d==='Ditolak'){note=prompt('Alasan penolakan:')||'';if(!note)return}setBusy(true);try{await operationsService.verifyPermission(x.ID,d,note);await loadIzin()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const ac=[{key:'Nama',label:'Anggota'},{key:'StatusKehadiran',label:'Status',render:(_,r)=><select value={r.StatusKehadiran} onChange={e=>setRows(v=>v.map(x=>x.AnggotaID===r.AnggotaID?{...x,StatusKehadiran:e.target.value}:x))}>{['Hadir','Izin','Sakit','Alpa'].map(x=><option key={x}>{x}</option>)}</select>},{key:'Catatan',label:'Catatan',render:(_,r)=><input value={r.Catatan} onChange={e=>setRows(v=>v.map(x=>x.AnggotaID===r.AnggotaID?{...x,Catatan:e.target.value}:x))}/>}];
 const ic=[{key:'NamaAnggota',label:'Anggota'},{key:'JenisPengajuan',label:'Jenis'},{key:'Alasan',label:'Alasan'},{key:'Status',label:'Status'},{key:'_',label:'Verifikasi',render:(_,r)=>(['Menunggu Verifikasi','Terkirim'].includes(r.Status)?<div className="row-actions"><button className="btn small" onClick={()=>verify(r,'Disetujui')}>Setujui</button><button className="btn small danger" onClick={()=>verify(r,'Ditolak')}>Tolak</button></div>:'—')}];
 return <><PageHeader eyebrow="KEHADIRAN" title="Absensi Massal & Izin" description="Kelola absensi kegiatan dan verifikasi pengajuan izin."/><section className="panel"><label>Kegiatan <select value={kid} onChange={e=>setKid(e.target.value)}><option value="">Pilih kegiatan...</option>{(acts||[]).map(x=><option key={x.ID} value={x.ID}>{x.NamaKegiatan} — {x.Tanggal} ({x.Status})</option>)}</select></label>{msg&&<div className="alert">{msg}</div>}<h3>Pengajuan Izin</h3><DataTable columns={ic} rows={izin} empty={kid?'Belum ada pengajuan izin.':'Pilih kegiatan.'}/><h3>Absensi Massal</h3><DataTable columns={ac} rows={kid?rows:[]} empty="Pilih kegiatan terlebih dahulu."/><div className="modal-actions"><button className="btn primary" disabled={!kid||busy} onClick={save}>{busy?'Memproses...':'Simpan Absensi Massal'}</button></div></section></>}
