import {useMemo,useState} from 'react';import {useAuth} from '../../context/AuthContext';import PageHeader from '../../components/common/PageHeader';import DataTable from '../../components/common/DataTable';import CrudModal from '../../components/common/CrudModal';import {assessmentService} from '../../services/assessment.service';import {step2Service} from '../../services/step2.service';import {moduleService} from '../../services/module.service';import {useRemoteData} from '../../hooks/useRemoteData';
const month=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`},today=()=>new Date().toISOString().slice(0,10);
export default function Page(){const {session}=useAuth();const canManage=session?.user?.Role==='ADMIN';const [per,setPer]=useState(month()),[member,setMember]=useState(''),[skk,setSkk]=useState(null),[changes,setChanges]=useState({}),[modal,setModal]=useState(null),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[pdfUrl,setPdfUrl]=useState('');
 const loader=useMemo(()=>()=>assessmentService.monthly(per),[per]);const {data,error,reload}=useRemoteData(loader,[per]);const {data:members}=useRemoteData(()=>moduleService.members(),[]);
 const rows=data?.rows||[],components=data?.components||[],entries=data?.entries||[];
 async function run(fn,success=''){setBusy(true);setMsg('');try{const x=await fn();if(success)setMsg(success);await reload();return x}catch(e){setMsg(e.message);throw e}finally{setBusy(false)}}
 async function openSkk(id){setMember(id);setBusy(true);try{const x=await assessmentService.skk(id);setSkk(x);const done={};(x.completion||[]).forEach(v=>done[v.ReferensiID]=true);setChanges(done)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function saveSkk(){const old=new Set((skk.completion||[]).map(x=>String(x.ReferensiID)));const diff=(skk.catalog||[]).filter(x=>old.has(String(x.ID))!==!!changes[x.ID]).map(x=>({MasterSKKID:x.ID,Checked:!!changes[x.ID]}));try{await run(()=>step2Service.saveSkk(member,today(),diff),'Checklist SKK tersimpan.');await openSkk(member)}catch(_){}}
 async function pdf(){const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;setPdfUrl('');try{const x=await run(()=>step2Service.generateAssessmentPdf(per),'PDF penilaian berhasil dibuat.');const url=new URL(x?.url||'');if(url.protocol!=='https:')throw new Error('Tautan laporan tidak dapat dibuka. Coba buat laporan kembali.');setPdfUrl(url.href);if(tab)tab.location.replace(url.href)}catch(e){if(tab)tab.close();setMsg(e.message||'PDF tidak dapat dibuka.')}}
 async function delEntry(x){if(!confirm('Hapus catatan nilai manual ini?'))return;try{await run(()=>step2Service.deleteAssessment(x.ID),'Catatan nilai dihapus.')}catch(_){}}
 async function delComp(x){if(!confirm(`Hapus komponen "${x.NamaKomponen}"?`))return;try{await run(()=>step2Service.deleteComponent(x.ID),'Komponen dihapus.')}catch(_){}}
 const summaryCols=[{key:'NTA',label:'NTA'},{key:'Nama',label:'Nama'},{key:'Krida',label:'Krida'},{key:'activityBonusScore',label:'Bonus kegiatan',render:v=>Number(v||0).toFixed(2)},{key:'score',label:'Nilai'},{key:'predicate',label:'Predikat'},{key:'_',label:'Aksi',render:(_,r)=><button className="btn small" onClick={()=>openSkk(r.ID)}>Checklist SKK</button>}];
 const entryCols=[{key:'Tanggal',label:'Tanggal'},{key:'NamaAnggota',label:'Anggota'},{key:'KomponenNama',label:'Komponen'},{key:'Poin',label:'Poin'},{key:'Catatan',label:'Catatan'},{key:'_',label:'Aksi',render:(_,r)=>canManage?<div className="row-actions"><button className="btn small" onClick={()=>{setEditing(r);setModal('entry')}}>Edit</button><button className="btn small danger" onClick={()=>delEntry(r)}>Hapus</button></div>:<span>Hanya lihat</span>}];
 const compCols=[{key:'Kode',label:'Kode'},{key:'NamaKomponen',label:'Komponen'},{key:'TipeSumber',label:'Sumber'},{key:'Bobot',label:'Bobot'},{key:'PoinMaksimum',label:'Maks Poin'},{key:'Status',label:'Status'},{key:'_',label:'Aksi',render:(_,r)=>canManage?<div className="row-actions"><button className="btn small" onClick={()=>{setEditing(r);setModal('component')}}>Edit</button>{String(r.TipeSumber).toUpperCase()!=='ABSENSI'&&<button className="btn small danger" onClick={()=>delComp(r)}>Hapus</button>}</div>:<span>Hanya lihat</span>}];
 const entryFields=[{key:'Tanggal',label:'Tanggal',type:'date',required:true},{key:'AnggotaID',label:'Anggota',type:'select',required:true,options:(members||[]).map(x=>({value:x.ID,label:x.Nama}))},{key:'KomponenID',label:'Komponen Manual',type:'select',required:true,options:components.filter(x=>String(x.TipeSumber).toUpperCase()==='MANUAL'&&String(x.Kode).toUpperCase()!=='SKK').map(x=>({value:x.ID,label:x.NamaKomponen}))},{key:'Poin',label:'Poin',type:'number',min:'0',step:'any',required:true},{key:'Catatan',label:'Catatan',type:'textarea',full:true}];
 const compFields=[{key:'NamaKomponen',label:'Nama Komponen',required:true},{key:'Kode',label:'Kode'},{key:'TipeSumber',label:'Tipe Sumber',type:'select',options:['MANUAL','ABSENSI'],required:true},{key:'Bobot',label:'Bobot',type:'number',min:'0.01',step:'any',required:true},{key:'PoinMaksimum',label:'Poin Maksimum',type:'number',min:'0.01',step:'any',required:true},{key:'Urutan',label:'Urutan',type:'number',min:'1'},{key:'Status',label:'Status',type:'select',options:['Aktif','Nonaktif'],required:true}];
 return <><PageHeader eyebrow="PENILAIAN" title="Penilaian & SKK" description="Rekap, nilai manual, komponen, checklist SKK, dan laporan PDF."/><section className="panel"><div className="toolbar toolbar-between"><label>Periode <input type="month" value={per} onChange={e=>setPer(e.target.value)}/></label><div className="row-actions"><button className="btn" onClick={pdf}>Buat PDF</button>{pdfUrl&&<a className="btn" href={pdfUrl} target="_blank" rel="noopener noreferrer">Buka PDF</a>}{canManage&&<button className="btn primary" onClick={()=>{setEditing(null);setModal('entry')}}>+ Input Nilai</button>}</div></div>{(error||msg)&&<div className="alert">{error||msg}</div>}<DataTable columns={summaryCols} rows={rows} empty="Belum ada data penilaian."/></section>
 <section className="panel section-gap"><div className="toolbar toolbar-between"><h2>Riwayat Nilai Manual</h2></div><DataTable columns={entryCols} rows={entries.filter(x=>String(x.KomponenKode||'').toUpperCase()!=='SKK')} empty="Belum ada input nilai manual."/></section>
 <section className="panel section-gap"><div className="toolbar toolbar-between"><h2>Komponen Penilaian</h2>{canManage&&<button className="btn" onClick={()=>{setEditing(null);setModal('component')}}>+ Komponen</button>}</div><DataTable columns={compCols} rows={components} empty="Belum ada komponen."/></section>
 {skk&&<section className="panel section-gap"><div className="toolbar toolbar-between"><h2>Checklist SKK — {skk.member?.Nama}</h2><button className="btn" onClick={()=>setSkk(null)}>Tutup</button></div><div className="check-grid">{(skk.catalog||[]).map(x=><label key={x.ID}><input type="checkbox" checked={!!changes[x.ID]} onChange={e=>setChanges(v=>({...v,[x.ID]:e.target.checked}))}/><span><strong>{x.KelompokSKK}</strong><br/>{x.Butir}</span></label>)}</div><div className="modal-actions"><button className="btn primary" disabled={busy} onClick={saveSkk}>Simpan Checklist</button></div></section>}
 <CrudModal open={modal==='entry'} title={editing?'Edit Nilai Manual':'Input Nilai Manual'} fields={entryFields} initial={editing||{Tanggal:today()}} saving={busy} onClose={()=>{setModal(null);setEditing(null)}} onSave={async x=>{try{await run(()=>step2Service.saveAssessment(x),'Nilai tersimpan.');setModal(null);setEditing(null)}catch(_){}}}/>
 <CrudModal open={modal==='component'} title={editing?'Edit Komponen':'Tambah Komponen'} fields={compFields} initial={editing||{TipeSumber:'MANUAL',Status:'Aktif',Urutan:1}} saving={busy} onClose={()=>{setModal(null);setEditing(null)}} onSave={async x=>{try{await run(()=>step2Service.saveComponent(x),'Komponen tersimpan.');setModal(null);setEditing(null)}catch(_){}}}/></>}
