import {useState} from 'react';import {useNavigate} from 'react-router-dom';import PageHeader from '../../components/common/PageHeader';import DataTable from '../../components/common/DataTable';import {step2Service} from '../../services/step2.service';import {useRemoteData} from '../../hooks/useRemoteData';
export default function Page(){const navigate=useNavigate();const {data,error,reload}=useRemoteData(()=>step2Service.notifications(),[]);const [detail,setDetail]=useState(null),[proof,setProof]=useState(null),[msg,setMsg]=useState('');const items=data?.items||[];
 async function read(){try{const ids=items.filter(x=>!x.read).map(x=>x.id);if(ids.length){await step2Service.markRead(ids);await reload()}}catch(e){setMsg(e.message)}}
 async function open(r){if(r.kind!=='permission-pending'){const path={kegiatan:'kegiatan',inventaris:'inventaris',surat:'surat',kas:'kas'}[r.module];if(path)navigate('/'+path+(r.module==='kegiatan'?'?kegiatanId='+encodeURIComponent(r.targetId):''));return;}try{const id=r.recordId;const x=await step2Service.permissionDetail(id);setDetail(x);setProof(null)}catch(e){setMsg(e.message)}}
 async function preview(){try{setProof(await step2Service.permissionProof(detail.ID))}catch(e){setMsg(e.message)}}
 async function verify(decision){let note='';if(decision==='Ditolak'){note=prompt('Alasan penolakan:')||'';if(!note)return}try{await step2Service.permissionVerify(detail.ID,decision,note);setDetail(null);setProof(null);setMsg(`Pengajuan ${decision.toLowerCase()}.`);await reload()}catch(e){setMsg(e.message)}}
 const cols=[{key:'title',label:'Notifikasi'},{key:'detail',label:'Keterangan'},{key:'read',label:'Status',render:v=>v?'Dibaca':'Baru'},{key:'_',label:'Aksi',render:(_,r)=><button className="btn small" onClick={()=>open(r)}>Detail</button>}];
 return <><PageHeader eyebrow="NOTIFIKASI" title="Notifikasi & Pengajuan" description="Tinjau notifikasi dan proses pengajuan yang membutuhkan tindakan."/><section className="panel"><div className="toolbar toolbar-between"><span>{data?.unread||0} belum dibaca</span><button className="btn" onClick={read}>Tandai Semua Dibaca</button></div>{(error||msg)&&<div className="alert">{error||msg}</div>}<DataTable columns={cols} rows={items} empty="Tidak ada notifikasi."/></section>
 {detail&&<section className="panel section-gap"><div className="toolbar toolbar-between"><h2>Detail Pengajuan</h2><button className="btn" onClick={()=>{setDetail(null);setProof(null)}}>Tutup</button></div><div className="detail-grid"><div><small>Anggota</small><b>{detail.NamaAnggota}</b></div><div><small>Kegiatan</small><b>{detail.KegiatanNama}</b></div><div><small>Jenis</small><b>{detail.JenisPengajuan}</b></div><div><small>Status</small><b>{detail.Status}</b></div><div className="wide"><small>Alasan</small><b>{detail.Alasan||'—'}</b></div></div><div className="toolbar"><button className="btn" disabled={!detail.BuktiNamaFile} onClick={preview}>Lihat Bukti</button>{['Menunggu Verifikasi','Terkirim'].includes(detail.Status)&&<><button className="btn primary" onClick={()=>verify('Disetujui')}>Setujui</button><button className="btn danger" onClick={()=>verify('Ditolak')}>Tolak</button></>}</div>{proof?.dataUrl&&<div className="proof-preview">{String(proof.mimeType).startsWith('image/')?<img src={proof.dataUrl} alt={proof.name}/>:<a className="btn" href={proof.dataUrl} target="_blank" rel="noreferrer">Buka {proof.name}</a>}</div>}</section>}</>}
